# Site settings
title: StagOS
email: support@stag-os.org
baseurl: "" # the subpath of your site, e.g. /blog/
url: stag-os.org # the base hostname & protocol for your site

copyright: StagOS

# Build settings
markdown: kramdown
